// DEVELOPMENT TEST
### TEST FOR PRODUCTS COLLECTION
### Get all Products
GET http://localhost:3000/products

### Create new Product
POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
    "name": "Smart Watch Series 8",
    "category": "Wearables",
    "price": 299.99,
    "stockQuantity": 75,
    "brand": "Apple",
    "rating": 4,
    "dateAdded": "2024-11-10",
    "isAvailable": true
}

### Update Product
PUT http://localhost:3000/products/ HTTP/1.1
Content-Type: application/json

{
    "name": "Smart Watch Series 8",
    "category": "Wearables",
    "price": 99.99,
    "stockQuantity": 5,
    "brand": "Apple",
    "rating": 5,
    "dateAdded": "2024-11-10",
    "isAvailable": true
}

### Delete Product
DELETE http://localhost:3000/sellers/ HTTP/1.1

### TEST FOR SELLERS COLLECTION
### Get all sellers
GET http://localhost:3000/sellers

### Create new Seller
POST http://localhost:3000/sellers HTTP/1.1
Content-Type: application/json

{
    "firstName": "Noah",
    "lastName": "Davis",
    "email": "test5@test5.com",
    "joinDate": "2023-11-30",
    "productsSold": 5,
    "isActive": true
}

### Update Seller
PUT http://localhost:3000/sellers/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Kim",
    "lastName": "Levis",
    "email": "test5@test5.com",
    "joinDate": "2023-11-30",
    "productsSold": 9,
    "isActive": true
}

### Delete Seller
DELETE http://localhost:3000/sellers/ HTTP/1.1


// PRODUCTION TEST
### TEST FOR PRODUCTS COLLECTION
### Get all Products
GET https://webservices-project2.onrender.com/products

### Create new Product
POST https://webservices-project2.onrender.com/products HTTP/1.1
Content-Type: application/json

{
    "name": "Smart Watch Series 8",
    "category": "Wearables",
    "price": 299.99,
    "stockQuantity": 75,
    "brand": "Apple",
    "rating": 4,
    "dateAdded": "2024-11-10",
    "isAvailable": true
}

### Update Product
PUT https://webservices-project2.onrender.com/products/ HTTP/1.1
Content-Type: application/json

{
    "name": "Smart Watch Series 8",
    "category": "Wearables",
    "price": 99.99,
    "stockQuantity": 5,
    "brand": "Apple",
    "rating": 5,
    "dateAdded": "2024-11-10",
    "isAvailable": true
}

### Delete Product
DELETE https://webservices-project2.onrender.com/products/ HTTP/1.1

### TEST FOR SELLERS COLLECTION
### Get all sellers
GET http://webservices-project2.onrender.com/sellers

### Create new Seller
POST http://webservices-project2.onrender.com/sellers HTTP/1.1
Content-Type: application/json

{
    "firstName": "Noah",
    "lastName": "Davis",
    "email": "test5@test5.com",
    "joinDate": "2023-11-30",
    "productsSold": 5,
    "isActive": true
}

### Update Seller
PUT http://webservices-project2.onrender.com/sellers/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Kim",
    "lastName": "Levis",
    "email": "test5@test5.com",
    "joinDate": "2023-11-30",
    "productsSold": 9,
    "isActive": true
}

### Delete Seller
DELETE http://webservices-project2.onrender.com/sellers/ HTTP/1.1